# Benchmark configuration for RustEx
# This file controls benchmark execution settings

[general]
# Warm up time for each benchmark (seconds)
warm_up_time = 3
# Measurement time for each benchmark (seconds)  
measurement_time = 5
# Number of samples per benchmark
sample_size = 100
# Confidence level for statistical analysis
confidence_level = 0.95

[benchmarks]
# Enable/disable specific benchmark groups
ast_parsing = true
complexity_calculation = true
full_extraction = true
visitor_performance = true
output_formatting = true
file_filtering = true
memory_usage = true
scalability = true

[reporting]
# Generate HTML reports
html_reports = true
# Output directory for reports
output_dir = "target/criterion"
# Enable detailed performance charts
charts = true

[thresholds]
# Performance regression thresholds (percentage)
parsing_threshold = 10.0
complexity_threshold = 15.0
extraction_threshold = 20.0
formatting_threshold = 5.0