include_docs = true
include_private = false
parse_dependencies = false
max_file_size = 10485760
output_format = "Rag"
plugins = []

[filters]
include = [
    "src/**/*.rs",
    "examples/**/*.rs",
]
exclude = [
    "target/**",
    "tests/**",
]
